/* CATALOGS */
INSERT INTO CATALOG (CATALOG_NAME, COUNTRY) VALUES('shoes', 'US');
INSERT INTO CATALOG (CATALOG_NAME, COUNTRY) VALUES('skates', 'US');

/* PRODUCTS */
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('airmin 999', 'fastest airmins', 'en', 'US', 'shoes');
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('airmin 555', 'faster airmins', 'en', 'US', 'shoes');
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('airmin 111', 'fast airmins', 'en', 'US', 'shoes');

INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('vancouverMMX', 'bc cascades', 'en', 'CA', 'skates');
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('calgary88', 'ab rockies', 'en', 'CA', 'skates');
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('montréal76', 'la deuxième population francophone', 'fr', 'CA', 'skates');
INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, LANGUAGE, COUNTRY, CATALOG_NAME) VALUES('québec76', 'au monde après Paris', 'fr', 'CA', 'skates');
