CREATE TABLE CATALOG(
  CATALOG_NAME VARCHAR(50) PRIMARY KEY,
  COUNTRY VARCHAR(2) NOT NULL
);

CREATE TABLE PRODUCT(
  PRODUCT_ID BIGINT AUTO_INCREMENT,
  PRODUCT_NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  LANGUAGE VARCHAR(3) NOT NULL,
  COUNTRY VARCHAR(2) NOT NULL,
  CATALOG_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (PRODUCT_ID),
  FOREIGN KEY (CATALOG_NAME) REFERENCES CATALOG(CATALOG_NAME)
);
